[programs.devnet]
backend = "74NXmpQ44hWKgAcB9epSQXS3ywmSv5qMbQeBMFzwHk3W"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/sean/.config/solana/id.json"

[scripts]
test = "node tests/backend.js"
